package Constants;

public enum FileNames {
    //lemma
    INDEX_UNCOMPRESS_VERSION1_DOCINFO,
    INDEX_UNCOMPRESS_VERSION1_INDEX,
    INDEX_UNCOMPRESS_VERSION1_POSTING_PTR,

    //stemma
    INDEX_UNCOMPRESS_VERSION2_DOCINFO,
    INDEX_UNCOMPRESS_VERSION2_INDEX,
    INDEX_UNCOMPRESS_VERSION2_POSTING_PTR,

    //lemma block compression
    INDEX_COMPRESS_VERSION1_DOCINFO,
    INDEX_COMPRESS_VERSION1_TERM,
    INDEX_COMPRESS_VERSION1_INDEX,
    INDEX_COMPRESS_VERSION1_POSTING_PTR,

    //stemma front coding
    INDEX_COMPRESS_VERSION2_DOCINFO,
    INDEX_COMPRESS_VERSION2_INDEX,
    INDEX_COMPRESS_VERSION2_POSTING_PTR,
    INDEX_COMPRESS_VERSION2_TERM
}
